language: go

# osx_image: xcode8.3

go:
 - 1.8
 - 1.9

os:
- linux
# - osx


before_install:
- go get github.com/golang/lint/golint
# - go get github.com/FiloSottile/vendorcheck
- go get github.com/alecthomas/gometalinter
# - go get github.com/gordonklaus/ineffassign
# - go get golang.org/x/tools/cmd/goimports
# - go get github.com/tsenart/deadcode
- gometalinter --install
# - go get github.com/Masterminds/glide
# - go get -u github.com/golang/dep/cmd/dep
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover


install:
# - glide install -v
# - dep ensure

script:
- gometalinter --config=gometalinter_config.json ./...
# - vendorcheck ./...
# -gcflags=-l resovle the problem of Monkey Patch test: http://www.jianshu.com/p/2f675d5e334e
# client.NewChecker is a inline function
- goveralls -v -race -service=travis-ci

# after_success:
# - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com
  slack: alastairruhm:AN7iL7hiZhXMjin6eWowNSax